name:  TF Automation
on:
    workflow_dispatch:
        inputs:
            workspace-env:
                description: "workspace to be create"
                type: choice
                options:
                    - dev
                    - qa
                    - prod
                default: dev


jobs:
    terraform_init:
        name: 'Terraform Plan'
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GCP_SA_KEY }}'
            
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'
            
           
            - name: Terraform Init
              continue-on-error: true
              run: |
                    
                    env_name=${{ inputs.workspace-env }}
                    chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"
                    "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"

                    chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_fmt.sh"
                    "${GITHUB_WORKSPACE}/.github/workflows/tf_fmt.sh"

                    chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_plan_check.sh"
                    "${GITHUB_WORKSPACE}/.github/workflows/tf_plan_check.sh"
                    
                    terraform workspace select -or-create ${{inputs.workspace-env }}
              shell: bash
            
            
                 
            






